### ISSUE TITLE
cds.join is not a function error

### ISSUE THREAD

**Issue by mohnark** [mapbox/tokml#42]
```
TypeError: cds.join is not a function
    at index.js:173:1
    at Array.map (<anonymous>)
    at linearring (index.js:173:1)
    at Object.Polygon (index.js:115:1)
    at Object.any (index.js:153:1)
    at index.js:28:1
    at Array.map (<anonymous>)
    at root (index.js:71:1)
    at tokml (index.js:16:1)
    at KmlBtn (kmlBtn.js:19:1)
```

**Comment by mohnark** [comment]
This issue is resolved since the coordinates need to be passed in an array
